# Generated by Django 5.2.4 on 2025-07-22 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
    ]
