INSERT INTO books (id, title, description, price, image_url)
VALUES
(1, 'Harry Potter - Rowling', 'Harry\'s adventures', 50, 'https://cdn4.libris.ro/img/pozeprod/839/838756-1.jpg'),
(2, 'The Hobbit: A Graphic Novel - Tolkin', 'A graphic novel of J.R.R. Tolkien\'s enchanting prequel to The Lord of the Rings.  When Thorin Oakenshield and his band of dwarves embark upon a dangerous quest to reclaim the hoard of gold stolen from them by the evil dragon Smaug, Gandalf the wizard sugg', 70, 'https://images-us.bookshop.org/ingram/9780063388468.jpg'),
(3, 'The Alice in Wonderland', 'I almost wish I hadn\'t gone down that rabbit-hole-and yet-and yet-it\'s rather curious, you know, this sort of life!  Presented here is a beautiful hardcover of Lewis Carroll\'s Alice series of books including Alice\'s Adventures in Wonderland and its sequel', 20, 'https://images-us.bookshop.org/ingram/9781954839045.jpg');

INSERT INTO books (id, title, description, price, image_url)
VALUES
(4, 'The Great Gatsby', 'A novel written by American author F. Scott Fitzgerald that explores themes of decadence, idealism, resistance to change, social upheaval, and excess, creating a portrait of the Jazz Age or the Roaring Twenties in the United States.', 25, 'view-source:https://m.media-amazon.com/images/M/MV5BMTkxNTk1ODcxNl5BMl5BanBnXkFtZTcwMDI1OTMzOQ@@._V1_.jpg'),
(5, '1984', 'Written by George Orwell, 1984 is a dystopian novel set in a totalitarian society where the government, led by the Party and its leader Big Brother, exercises complete control over all aspects of life.', 18, 'https://upload.wikimedia.org/wikipedia/commons/5/51/1984_first_edition_cover.jpg'),
(6, 'To Kill a Mockingbird', 'Harper Lee\'s 1960 Pulitzer Prize-winning novel that deals with issues of racism, injustice, and moral growth in the small town of Maycomb, Alabama, as seen through the eyes of young Scout Finch.', 22, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg/500px-To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg'),
(7, 'Pride and Prejudice', 'A classic romantic novel by Jane Austen, first published in 1813, that deals with the issues of social class, marriage, and morality in early 19th-century England.', 15, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/PrideandPrejudiceCH3.jpg/500px-PrideandPrejudiceCH3.jpg'),
(8, 'The Catcher in the Rye', 'J.D. Salinger\'s 1951 novel about the adolescent Holden Caulfield, who is disillusioned by the phoniness of the world around him and becomes alienated from society.', 19, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/The_Catcher_in_the_Rye_%281951%2C_first_edition_cover%29.jpg/500px-The_Catcher_in_the_Rye_%281951%2C_first_edition_cover%29.jpg'),
(9, 'The Lord of the Rings: The Fellowship of the Ring', 'The first novel in J.R.R. Tolkien\'s epic fantasy series, where young hobbit Frodo Baggins embarks on a perilous journey to destroy the One Ring and save Middle-earth.', 35, 'https://en.wikipedia.org/wiki/File:Lord_Rings_Fellowship_Ring.jpg');
